%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#727272',
      'textColor': '#000'
    }
  }
}%%

erDiagram

user {
  bigint id
  varchar username
  varchar email
  varchar phone
  datetime created_at
  datetime updated_at
}
