%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#727272',
      'textColor': '#000'
    }
  }
}%%

erDiagram

activities {
  string id "uuidv4"
  int activity_type
  int juz "nullable"
  int surah "nullable"
  int start_ayah "nullable"
  int end_ayah "nullable"
  bool mark_surah_done "nullable"
  bool mark_juz_done "nullable"
  int repeat
  timestampz occured_at
}
